var floor1Data =
{
    floor1Title: "出荷情报",
    floor1UlData: ["手办", "情报", "宅闻", "评测", "学姿势"],
    floor1Datas: [
        [
            {
                imgSrc: " ../images/index/floor1-img1.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],
        [
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img1.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],
        [
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img1.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],
        [
            {
                imgSrc: " ../images/index/floor1-img1.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],
        [
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],
        [
            {
                imgSrc: " ../images/index/floor1-img1.jpg",
                headerImg: "../images/index/authorImg1.jpg",
                title: "青春期笨蛋不做兔女郎学姐的梦 樱岛麻衣 晴着ver.",
                author: "枫叶飘飘",
                time: "2018年9月",
            },
            {
                imgSrc: " ../images/index/floor1-img2.jpg",
                headerImg: "../images/index/authorImg2.jpg",
                title: "请问您今天要来点兔子吗？ 智乃夏制服开箱评测",
                author: "好吧君",
                time: "2018年5月",
            },
            {
                imgSrc: " ../images/index/floor1-img3.jpg",
                headerImg: "../images/index/authorImg3.jpg",
                title: "【评测】ねんどろいどNo.801-No.802 君の名は",
                author: "平沢憂",
                time: "2018年4月",
            },
            {
                imgSrc: " ../images/index/floor1-img4.jpg",
                headerImg: "../images/index/authorImg4.jpg",
                title: "PLUM 偶像大师灰姑娘女孩 橘爱丽丝 原型公开",
                author: "做一个开心的吃货",
                time: "2019年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img5.jpg",
                headerImg: "../images/index/authorImg5.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
            {
                imgSrc: " ../images/index/floor1-img6.jpg",
                headerImg: "../images/index/authorImg6.jpg",
                title: "来和我跳一支舞吗？少女前线HK416星之茧1/8手办正式出荷",
                author: "Tmore",
                time: "2020年1月",
            },
        ],



    ],
}




console.log(JSON.stringify(floor1Data))